dataset:
  dataset_name: 'ECG5000'
  in_channels: 1
  data_scaling: True
  batch_sizes:
    vqvae: 128
  num_workers: 16

model_params:
  LR: 0.001 #0.01
  weight_decay: 0.001 #0.00001

trainer_params:
  gpus:
    - 0
  max_epochs:
    vqvae: 1500
    barlowvqvae: 1500

encoder:
  dim: 64
  dropout_rate: 0.0
  n_resnet_blocks: 4
  downsampled_width: 8

decoder:
  dim: 64
  dropout_rate: 0.0
  n_resnet_blocks: 4

VQVAE:
  n_fft: 8
  codebook:
    size: 32
    dim: 64
  decay: 0.8
  commitment_weight: 1
  emb_dropout: 0.
  perceptual_loss_weight: 0

barlow_twins:
  proj_hid: 4096
  proj_out: 4096
  gamma: 1

representations:
  test_stage1: True
  test_stage2: False
